### ISSUE TITLE
NullPointer when BlipClient.openBlipThread is called

### ISSUE THREAD

**Issue by danielulrik** [takenet/blip-chat-android#2]
Im getting this error when i call BlipClient.openBlipThread(getActivity(), appkey, blipOptions);

net.take.blipchat.activities.ThreadActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.hide()' on a null object reference

**Comment by andrebires** [comment]
Hi, thanks for the report.

It was fixed in the 2.1.24 version of the package.
